spring.application.name=github-portfolio-analyzer
server.port=8080


# GitHub API Configuration
github.api.url=https://api.github.com

logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.com.github.portfolio=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent
